### ISSUE TITLE
Фича - уведомления в вебинтерфейсе о невалидности токенов

### ISSUE THREAD

**Issue by zmm** [moevm/zoom_youtube_publisher#18]
В чем состоит проблема - токены авторизации в сервисах устаревают (ниже лог, который показывает как это выглядит для  сервиса), и пользователю необходимо 1) об этом узнать 2) получить ссылки для освежения токенов

2021-11-18 08:32:57,103 INFO - App started
2021-11-18 08:32:57,114 INFO - Started publishing thread
2021-11-18 08:33:01,371 ERROR - Traceback (most recent call last):
  File "/app/youtube.py", line 102, in upload_video
    response = self.resumable_upload(insert_request(self.client))
  File "/app/youtube.py", line 118, in resumable_upload
    status, response = insert_request.next_chunk()
  File "/usr/local/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/googleapiclient/http.py", line 1004, in next_chunk
    resp, content = _retry_request(
  File "/usr/local/lib/python3.10/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google_auth_httplib2.py", line 245, in request
    self.credentials.refresh(self._request)
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/credentials.py", line 214, in refresh
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/app/publisher.py", line 68, in run
    video = self.youtube.upload_video(
  File "/app/youtube.py", line 104, in upload_video
    self.update_token()
  File "/app/youtube.py", line 167, in update_token
    self.access_token = response["access_token"]
KeyError: 'access_token'
2021-11-18 08:33:01,371 INFO - Joined publishing thread

**Comment by zmm** [comment]
В текущем интерфейсе не понятно, что делать, чтобы возобновить работу.
